### ISSUE TITLE
codeblocks in embeds are not visible at all

### ISSUE THREAD

**Issue by Slluxx** [DiscordStyles/MinimalCord#30]
codeblocks in embeds are not visible at all

```css
#app-mount pre code, #app-mount code.inline {
    background: #1c2026!important;
}


#app-mount .textContainer-36wgKK {
    border: 1px solid!important;
    background: var(--background-dark)!important;
    border-color: var(--background-dark)!important;
    border-radius: var( --border-radius) var(--border-radius) 0 0!important;
}
```

~~this fixes it~~ nvm now regular codeblocks are invisible
