### ISSUE TITLE
PFP decorations off centered.

### ISSUE THREAD

**Issue by gustish** [DiscordStyles/MinimalCord#34]
The latest avatar decorations seem to be off centered a bit, not that biggest deal but so you know.

![image](https://github.com/DiscordStyles/MinimalCord/assets/134213266/87d7b79b-f0f3-493b-9f10-5b9accdfa87e)

**Comment by LeviSnoot** [comment]
Not read up enough to contribute directly to the project but here's the CSS snippet I used to fix it:

```css
.avatarDecoration__14b3c {
    left: calc((9px) - (var(--custom-message-avatar-decoration-size) - var(--custom-message-avatar-size))/2) !important;
    margin-top: calc(2px - var(--custom-message-spacing-vertical-container-cozy) - (var(--custom-message-avatar-decoration-size) - var(--custom-message-avatar-size))/2) !important;
}
```

**Comment by 1Naim** [comment]
The updated class for latest Discord as of time of writing

```css
.avatarDecoration_f9f2ca {
    left: calc((9px) - (var(--custom-message-avatar-decoration-size) - var(--custom-message-avatar-size))/2) !important;
    margin-top: calc(2px - var(--custom-message-spacing-vertical-container-cozy) - (var(--custom-message-avatar-decoration-size) - var(--custom-message-avatar-size))/2) !important;
}
```

No modifications made from the above snippet except for updating the css class.
